### ISSUE TITLE
[nioEventLoopGroup-2-1] WARN org.cloudburstmc.netty.handler.codec.raknet.server.RakServerRateLimiter - [/192.168.1.209] Blocked because packet limit was reached null disconnected

### ISSUE THREAD

**Issue by pattarom** [Pugmatt/BedrockConnect#503]
### What happened?

I run BedrockConnect in a container. 
Sometimes I cannot connect and looking in the log I find this error:

> [nioEventLoopGroup-2-1] WARN org.cloudburstmc.netty.handler.codec.raknet.server.RakServerRateLimiter - [/192.168.1.209] Blocked because packet limit was reached
>null disconnected

For installing I use this docker composer configuration:
I try to set packet limit to extreme values, but issue often returns

To resume I must manually restart the container

```
version: "3.8"

services:
  bedrockconnect: 
    image: strausmann/minecraft-bedrock-connect:latest
    restart: always
    environment:
      MYSQL_HOST: "db"
      MYSQL_USER: "bedrock"
      MYSQL_PASS: "bedrock"
      MYSQL_DB: "bedrock"
      CUSTOM_SERVERS: "/config/serverlist.json"
      FEATURED_SERVERS: false
      USER_SERVERS: true
      PACKET_LIMIT: 2000
      offline_packet_limit: 50
      global_packet_limit: 150000
      #BRC_VERSION: 1.45
      
    ports:
      - 19132:19132/udp
    depends_on:
      - db
    volumes:
     #- bedrockconnect:/config
     - /home/michele/mcbedrockc-data:/config

  db: 
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwbedrock
      - MYSQL_PASSWORD=bedrock
      - MYSQL_USER=bedrock
      - MYSQL_DATABASE=bedrock
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
    ports:
      - 3306:3306
    volumes:
      - bedrockconnect_database:/var/lib/mysql

volumes:
  bedrockconnect:
    driver: local
  bedrockconnect_database:
    driver: local
```

### Expected Behaviour?

I can connect without issues.

### Minecraft Bedrock Version

1.21.03 but issue was still present in earlier versions

### Console

XBOX and Windows PC
